### ISSUE TITLE
Formal methods for concurrent and real-time systems

### ISSUE THREAD

**Issue by jff** [fme-teaching/fm-courses#23]
<a href="https://github.com/luigiapetre"><img src="https://avatars3.githubusercontent.com/u/37589124?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [luigiapetre](https://github.com/luigiapetre)**
_Tuesday Aug 21, 2018 at 09:35 GMT_
_Originally opened as https://github.com/luigiapetre/Formal-Methods-Courses/issues/23_

----

Course code, if applicable: 088882
University hosting the course: Politecnico di Milano
Contact person: Pierluigi San Pietro, pierluigi.sanpietro@polimi.it
Concepts taught: Theory and practice of specification and verification of real-time systems, with particular focus on transition systems, timed automata, model checking and temporal logic;
Hoare’s method for program specification and verification. Examples of tools and applications (Prism, Spin, Javapathfinder, etc.)
Tools used: Uppaal.
Webpage: https://tinyurl.com/26z2c78v

**Comment by sanpietr** [comment]
Updated the content.
