### ISSUE TITLE
Software Verification

### ISSUE THREAD

**Issue by jff** [fme-teaching/fm-courses#48]
<a href="https://github.com/brijeshdongol"><img src="https://avatars0.githubusercontent.com/u/2255629?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [brijeshdongol](https://github.com/brijeshdongol)**
_Friday Apr 12, 2019 at 13:23 GMT_
_Originally opened as https://github.com/luigiapetre/Formal-Methods-Courses/issues/48_

----

Course code, if applicable: COS6020-B
University hosting the course: University of Bradford
Contact person: ??? 
Concepts taught: Classical logic, formal specification, model checking, reactive systems, program verification
Tools used:
Webpage: https://www.bradford.ac.uk/repos/modules/2020-21/cos6020-b.php

**Comment by jff** [comment]
@luigiapetre @brijeshdongol The link is not working and we don't have any contact information. A quick search online doesn't reveal much information (apart from old editions of the course). My suggestion is to close this issue.

**Comment by brijeshdongol** [comment]
@jff Yes, let's close it. I couldn't find any information on this either.
